export { default as Header } from "./layout/Header/Header";
export { default as Footer } from "./layout/Footer";
export { default as Banner } from "./layout/Banner";
export { default as Cart } from "./layout/Card/Cart";
export { default as User } from "./layout/User/User";
export { default as MetaData } from "./layout/MetaData";
export { default as Product } from "./Product/Product";
export { default as Loader } from "./layout/Loader/Loader";
export { default as Productdetails } from "./Productdetails/Productdetails";
export {default as Search} from './layout/Search';
export {default as Login} from './layout/User/Login/Login';
export {default as Register} from './layout/User/Register/Register';
export {default as Profile} from './layout/User/Profile/Profile';
export {default as ProtectedRoute} from './Route/ProtectedRoute';
export {default as Updateprofile} from './layout/User/Updateprofile/Updateprofile';
export {default as UpdatePassword} from './layout/User/UpdatePassword/UpdatePassword';
export {default as ForgotPassword} from './layout/User/ForgotPassword/ForgotPassword';
export {default as NewPassword} from './layout/User/NewPassword/NewPassword';
export {default as PageHader} from './layout/PageHader/PageHader';
export {default as Shipping} from './layout/Card/Shipping/Shipping';
export {default as ConfirmOrder} from './layout/Card/ConfirmOrder/ConfirmOrder';
export {default as Payment} from './layout/Card/Payment/Payment';
export {default as Success} from './layout/Card/Success/Success';
export {default as ListReviews} from './Review/ListReviews';